# Generated by Django 4.1.4 on 2022-12-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='cover',
            field=models.ImageField(default='music_cover/default.jpg', upload_to='music_cover'),
        ),
    ]
