# Generated by Django 4.1.4 on 2022-12-20 06:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_cover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='CommentsLikes',
            new_name='CommentLike',
        ),
        migrations.RenameModel(
            old_name='PostFavorites',
            new_name='PostFavorite',
        ),
        migrations.RenameModel(
            old_name='PostLikes',
            new_name='PostLike',
        ),
    ]
